# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d18v/8tepA4EWhSG2lYUPH9wdewSnz7kMUe2kdBtoR3VXZFojGhiQwOOy1mHrs9pXMyoppRBgHm7UV5QYwnGRdoHY09ZQx6PO6TLXRNy/kt7fLNS83M9xAnJaoSYk154s57TgXUebYwEv+9YHTKkt611bzWAmt/ezHKwOd4OmdzaP+2YnOC9RlgfH4Ry5PChnZXv9sqxWUHlvFWlTTs22iJ+zN2V0SKG3wqEMDkSbZiD75m5YtEA7YLQ5BVQgxmty0WW8PhgFH/qwBwbRhynyDN9JnxP1fP6bLxK1d9XmHDQm2TmpXVJgJ0iQMSVNc6VMD/TEe/JZPSsRuZHStwol57a/D64VXHVFMTfijzhECV69cq5FmLJf9wnf+21YOrpBMiIziqaiOM1aF3xpjva81AllQO34WhBbiPPB7huD9MH/eeXPO1wYm6pakDnUfXHEWqvkcY72iG1Sagn9LLHa0qSxJLfw9GhEyJr4/kM5X0y7ijwUqYXdBtNGrI/ifpxtR2eqoiBcdiKnu03AzDOpB4PhAuhjTsfhixbO8g3Us9AJ/wK/7ckNOPmy+iny0kPjAFsyjdRa7xEWzP4aIHo7wC5lQ5UxEh+vz/2wL0R8CFFXT1TwSxQ3GKVcytet5l+ifJOxn9IChxo8c4vRYK6ZuqUO0XE89x0lihQyqLthWk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
