appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: d18v/8tepA4EWhSG2lYUPH9wdewSnz7kMUe2kdBtoR3VXZFojGhiQwOOy1mHrs9pXMyoppRBgHm7UV5QYwnGRdoHY09ZQx6PO6TLXRNy/kt7fLNS83M9xAnJaoSYk154s57TgXUebYwEv+9YHTKkt611bzWAmt/ezHKwOd4OmdzaP+2YnOC9RlgfH4Ry5PChnZXv9sqxWUHlvFWlTTs22iJ+zN2V0SKG3wqEMDkSbZiD75m5YtEA7YLQ5BVQgxmty0WW8PhgFH/qwBwbRhynyDN9JnxP1fP6bLxK1d9XmHDQm2TmpXVJgJ0iQMSVNc6VMD/TEe/JZPSsRuZHStwol57a/D64VXHVFMTfijzhECV69cq5FmLJf9wnf+21YOrpBMiIziqaiOM1aF3xpjva81AllQO34WhBbiPPB7huD9MH/eeXPO1wYm6pakDnUfXHEWqvkcY72iG1Sagn9LLHa0qSxJLfw9GhEyJr4/kM5X0y7ijwUqYXdBtNGrI/ifpxtR2eqoiBcdiKnu03AzDOpB4PhAuhjTsfhixbO8g3Us9AJ/wK/7ckNOPmy+iny0kPjAFsyjdRa7xEWzP4aIHo7wC5lQ5UxEh+vz/2wL0R8CFFXT1TwSxQ3GKVcytet5l+ifJOxn9IChxo8c4vRYK6ZuqUO0XE89x0lihQyqLthWk=
conda_forge_output_validation: true
